spring:
  application:
    name: batch-data-migration
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/sample_restaurants
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sample_restaurants
    username: admin
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
